name: scoring CI/CD 
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [3.12]
    services:
      redis:
        image: redis:latest    # Use the latest Redis image from Docker Hub
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 3
        ports:
          - 6379:6379          # Map the Redis port to the host machine
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.4
      - name: Install dependencies
        run: poetry install
      - name: Run linter flake8
        run: |
          poetry run flake8 --max-line-length=120
      - name: Run server
        run: |
          poetry run python api.py
      - name: Run tests
        run: |
          poetry run pytest ./tests
